name: mataginews
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.7.0
  http: ^0.12.0+4
  flutter_spinkit: ^4.1.2
  auto_size_text: ^2.1.0
  flutter_auth_buttons: ^0.6.0
  google_sign_in: ^4.1.4
  firebase_auth: ^0.15.5+2
  firebase_core: ^0.4.4+2
  cloud_firestore: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - assets/images/
  #  - images/a_dot_ham.jpeg
  fonts:
    - family: Exo
      fonts:
        - asset: assets/fonts/Exo-Black.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
